Add PyPI publishing in GH workflow
repository-service-tuf/repository-service-tuf-cli pull request #254
Opened 2023-04-12 21:52 UTC by KAUTH

The process of publishing the package to PyPI will now be automated.

Note: If we want we can test this first before merging by releasing to TestPyPI (will need a new token with project scope).

Closes #238

2023-04-13 06:35 UTC, kairoaraujo commented
Hi @KAUTH, thank you! It looks good.
I think adding the configuration for test.pypi.org before uploading it to the PyPI production repo is important.

2023-04-13 21:34 UTC, KAUTH commented
> Hi @KAUTH, thank you! It looks good. I think adding the configuration for test.pypi.org before uploading it to the PyPI production repo is important.

Agreed, I added it :smiley: The only thing left is for a repo and PyPI admin to match `PYPI_API_TOKEN` and  `TEST_PYPI_API_TOKEN` secrets.

2023-04-14 06:28 UTC, kairoaraujo commented
> > Hi @KAUTH, thank you! It looks good. I think adding the configuration for test.pypi.org before uploading it to the PyPI production repo is important.
> 
> Agreed, I added it 😃 The only thing left is for a repo and PyPI admin to match `PYPI_API_TOKEN` and `TEST_PYPI_API_TOKEN` secrets.

I will work on this part ;)

2023-04-23 10:50 UTC, KAUTH commented
Let me know if we need anything from my side before closing this PR :smiley:

2023-04-24 07:56 UTC, kairoaraujo requested changes

2023-04-24 07:56 UTC, kairoaraujo commented on .github/workflows/cd.yml
> +        if: github.repository == 'vmware/repository-service-tuf-cli'
```suggestion
        if: github.repository == 'repository-service-tuf/repository-service-tuf-cli'
```

2023-04-24 07:56 UTC, kairoaraujo commented on .github/workflows/cd.yml
> +          password: ${{ secrets.PYPI_API_TOKEN }}
```suggestion
```
We can use [trusted publishing](https://github.com/marketplace/actions/pypi-publish#trusted-publishing) with this action.
I already configured it on PyPI.

2023-04-30 14:50 UTC, KAUTH commented on .github/workflows/cd.yml
> +          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
I believe I adjusted it, I am not sure if the extra env variables are needed at each publish step but I added them following the `gh-action-pypi-publish` docs.

2023-05-01 10:03 UTC, kairoaraujo approved these changes

2023-05-01 10:03 UTC, merged