Add information about pending signatures
repository-service-tuf/repository-service-tuf-cli pull request #377
Opened 2023-09-12 15:53 UTC by ivanayov

This change outputs a warning and a number of pending root signatures during DAS bootstrap ceremony

Fixes #355

# Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality not to work as expected)

# Additional requirements
- [x] Tests have been added for the bug fix or new feature
- [n/a ] Docs have been added for the bug fix or new feature

# Code of Conduct
By submitting this PR, you agree to follow our [Code of Conduct](CODE_OF_CONDUCT.rst).

- [x] I agree to follow this project's Code of Conduct

2023-09-13 06:43 UTC, kairoaraujo requested changes
Hi @ivanayov,

Thank you for your first contribution to RSTUF :tada:  It is amazing having you here!

I left a few comments here, feel free to discuss them.

Tips:
You can run `make reformat` to fix PEP8 and formatting.

We also recommend [enable the `pre-commit`](https://github.com/repository-service-tuf/repository-service-tuf-cli/blob/main/CONTRIBUTING.rst#running-checks-with-pre-commit)

2023-09-13 06:43 UTC, kairoaraujo commented on repository_service_tuf/cli/admin/ceremony.py
> +            )
It's preferable to use [f-strings](https://peps.python.org/pep-0498/) and you can reuse the calculation you did above
```suggestion
        console.print(
            f"Root is not trustworthy yet. {pending_signatures} pending signatures are left."
        )
```

2023-09-13 09:52 UTC, MVrachev commented on repository_service_tuf/cli/admin/ceremony.py
> +    if root.signatures < setup.threshold[Roles.ROOT]:
This also has a benefit it makes it clearer about what the math: `setup.threshold[Roles.ROOT] - len(metadata[Roles.ROOT].signatures)` calculates.

2023-09-13 11:33 UTC, ivanayov commented on tests/unit/cli/admin/test_ceremony.py
> +            "20",  # What is the key threshold for root role signing?
It's a good catch! We could expand the issue or I can do in a follow-up?

2023-09-13 12:34 UTC, kairoaraujo commented on tests/unit/cli/admin/test_ceremony.py
> +            "20",  # What is the key threshold for root role signing?
As you wish 😄

2023-09-13 14:17 UTC, ivanayov commented
Pushed again, as previously I pushed without the changes by mistake.

2023-09-14 12:38 UTC, ivanayov commented
@kairoaraujo It has the sslib fix now and is ready to run

2023-09-15 13:56 UTC, MVrachev commented on repository_service_tuf/cli/admin/ceremony.py
> +            f" {pending_signatures} pending signatures are left.",
```suggestion
            "Root is not trustworthy yet,"
            f" {pending_signatures} pending signature(s) left.",
```

2023-09-19 17:03 UTC, ivanayov commented
Forgot to update the test after changing the layout.

2023-09-19 17:10 UTC, ivanayov commented
Forse-pushed the test update.

2023-09-20 08:24 UTC, MVrachev approved these changes

2023-09-20 08:24 UTC, MVrachev commented
@kairoaraujo you are required to give approval otherwise we cannot merge.

2023-09-20 09:08 UTC, kairoaraujo approved these changes

2023-09-21 17:42 UTC, merged