Task/331 cli artifact delete command
repository-service-tuf/repository-service-tuf-cli pull request #483
Opened 2024-01-09 15:07 UTC by fsavoia

# Description
This task is about creating the command to delete artifacts from TUF Metadata using RSTUF API.

#331 

# Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality not to work as expected)

# Additional requirements
- [x] Tests have been added for the bug fix or new feature
- [x] Docs have been added for the bug fix or new feature

# Code of Conduct
By submitting this PR, you agree to follow our [Code of Conduct](CODE_OF_CONDUCT.rst).

- [x] I agree to follow this project's Code of Conduct

2024-01-11 13:32 UTC, MVrachev requested changes
Great work @fsavoia!
I left a few comments.

Additionally, we usually don't push the `png` file changes as they come from underline changes of the underline tool `plantuml`.

2024-01-11 13:32 UTC, MVrachev commented on tests/unit/helpers/test_cli.py
> +            create_artifact_delete_payload_from_filepath(
Would be better and more readable if you assign a variable `result` to the `create_artifact_delete_payload_from_filepath` call and check it with an assert.

2024-01-11 13:32 UTC, MVrachev commented on tests/unit/cli/artifact/test_delete.py
> +        with client.isolated_filesystem():
Nice!
I haven't used that, but it seems useful!

2024-01-11 13:32 UTC, MVrachev commented on tests/unit/cli/artifact/test_delete.py
> +    def test_delete_without_api_server(self, client, test_context):
One more test will be nice 
`test_delete_not_passing_api_server_but_existing_in_settings`
where your `api_server` will be inside `settings.SERVER`.

2024-01-11 13:32 UTC, MVrachev commented on tests/unit/helpers/test_cli.py
> +    def test_create_artifact_delete_payload_from_filepath(
One more test will be useful:
`create_artifact_add_payload_from_filepath_without_path`

2024-01-12 10:41 UTC, fsavoia commented
Thank @MVrachev  for your good suggestions. I updated the PR with the improvements.

2024-01-12 10:58 UTC, MVrachev requested changes
One small think is left.

2024-01-12 10:58 UTC, MVrachev commented on docs/source/_static/repository-service-tuf-cli-C1.png
I didn't mean you need to remove the changes in the file `docs/source/devel/repository_service_tuf.cli.artifact.rst`.
We do want the documentation for `rstuf artifact delete` as you included it.
Can you please remove this commit https://github.com/repository-service-tuf/repository-service-tuf-cli/pull/483/commits/b09d806fcaf07c17e62cb5ccd304807b07a4ec47 and instead remove those `png` file changes.
These files are the ones changed by `plantuml`.

2024-01-12 11:06 UTC, fsavoia commented on docs/source/_static/repository-service-tuf-cli-C1.png
Now I got it Martin.

2024-01-12 11:57 UTC, MVrachev commented
Thanks @fsavoia for your work!
Just to let you know I meant removing the binary files:
- `docs/source/_static/repository-service-tuf-cli-C1.png`
- `docs/source/_static/repository-service-tuf-cli-C2.png`
- `docs/source/_static/repository-service-tuf-cli-C3.png`
from our changes, but this is not a big deal and we can approve it.
I wanted to let you know for future to not include them your prs.

2024-01-12 11:59 UTC, MVrachev approved these changes

2024-01-12 17:01 UTC, MVrachev approved these changes

2024-01-12 17:10 UTC, merged