Add alternative admin cli
repository-service-tuf/repository-service-tuf-cli pull request #523
Opened 2024-03-04 15:15 UTC by lukpueh

Added commands:

- `rstuf admin2 ceremony`
- `rstuf admin2 update`
- `rstuf admin2 sign`

Previous work, related discussion, and detailed reasons for the re-write can be found in https://github.com/repository-service-tuf/repository-service-tuf-cli/pull/477 and https://github.com/repository-service-tuf/repository-service-tuf-cli/pull/490. These PRs are superseded by this PR.

Currently, the cli does not interact with the RSTUF API, but reads input data from files passed as cli arguments (update, sign) and optionally writes output data to file using the `--payload-out` option (ceremony, update, sign).

Preliminary API integration can be found in https://github.com/repository-service-tuf/repository-service-tuf-cli/pull/477. I suggest to re-implement this in a separate PR, as well as any presentation improvements discussed in https://github.com/repository-service-tuf/repository-service-tuf-cli/pull/477.

2024-03-12 13:15 UTC, MVrachev requested changes
We have agreed that functionality, code optimizations, UI, docs and tests changes will be undressed with following prs.
The requirement for this pr is to @kairoaraujo, @lukpueh and me to agree on the user flow.

I will split my review by commands.
I have reviewed only sign and md update flows.

## Sign

Only two small comments:
1. Give information to the user whether and where the payload will be saved.
2. I think we can rename `-o` to `-s` and `----payload-out` to `--save-path` options.

## Metadata Update

1. When asking about threshold changes, the default value should be `n` or no.
2. Add a question asking for custom online key name
3. Give information to the user whether and where the payload will be saved.
4. I think we can rename `-o` to `-s` and `----payload-out` to `--save-path` options.

As a note for metadata update: we have decided to not use authorization, but the metadata update ceremony makes sure that you have at least one signature added.

Other improvements we have discussed will be documented in an issue.

I will review the ceremony flow in the next review.

2024-03-12 13:37 UTC, lukpueh commented on repository_service_tuf/cli/admin2/sign.py
> +    if prev_root_in:
TODO: raise if not prev_root_in and root_md version is `>1`,

2024-03-18 09:29 UTC, lukpueh commented
> 3. Give information to the user on whether and where the payload will be saved.

@MVrachev, IIRC, we agreed that it's okay to merge this without API integration. What do think about, in the meanwhile, either
- warn, if the user does not provide the `-s` flag, or
- make the flag required?

Even thought the cli without API integration is experimental, we don't want to frustrate the user, by letting them go through the dialog without anything happening in the end.

2024-03-18 10:26 UTC, MVrachev commented
> > 3. Give information to the user on whether and where the payload will be saved.
> 
> @MVrachev, IIRC, we agreed that it's okay to merge this without API integration. 

Yes, that's correct.

> What do think about, in the meanwhile, either
> 
> * warn, if the user does not provide the `-s` flag, or
> * make the flag required?

I am fine either way.
Maybe a warning will be better as we can also mention that the commands are experimental.
Then, when all of the features are added and we are replacing the current commands we would just remove one warning for each command.

> Even thought the cli without API integration is experimental, we don't want to frustrate the user, by letting them go through the dialog without anything happening in the end.

Agree.

2024-03-22 12:34 UTC, lukpueh commented on repository_service_tuf/cli/admin2/sign.py
> +    if prev_root_in:
Fixed in e1ef9302c41e2739ad8c4c980a74b7d08b572bcb

2024-03-26 15:43 UTC, MVrachev approved these changes
All comments stopping this pr from merge were addressed.

We have a lot more to do, but this is a great start!

Awesome job @lukpueh!

PS: before merging we would have to make sure we are on top of the latest main changes and functional tests should pass.

2024-03-26 15:46 UTC, MVrachev commented
As this is a big change: do you have to ask, add, or want to change anything before merging @kairoaraujo?

2024-03-26 16:05 UTC, kairoaraujo commented
> As this is a big change: do you have to ask, add, or want to change anything before merging @kairoaraujo?

Not to add, it is isolated :)

2024-03-26 16:07 UTC, merged